# Generated by Django 4.1.7 on 2023-05-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passsword',
            new_name='password',
        ),
    ]
